var responseTimeDistributions = 
{
    "categories":[
        "0ms",
        "10ms",
        "20ms",
        "30ms",
        "40ms",
        "50ms",
        "60ms",
        "70ms",
        "80ms",
        "90ms",
        "100ms",
        "110ms"
    ],
    "distributions":[
        {
            "name":" GOTO_INDEX_PAGE",
            "data":[
                29,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            ]
        },
        {
            "name":" UPLOAD_FILE",
            "data":[
                0,
                20,
                4,
                3,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0
            ]
        }
    ]
}