var responseTimeDistributions = 
{
    "categories":[
        "0ms",
        "10ms",
        "20ms",
        "30ms",
        "40ms",
        "50ms",
        "60ms",
        "70ms",
        "80ms",
        "90ms",
        "100ms",
        "110ms",
        "120ms",
        "130ms",
        "140ms",
        "150ms",
        "160ms",
        "170ms",
        "180ms"
    ],
    "distributions":[
        {
            "name":" GOTO_INDEX_PAGE",
            "data":[
                4,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            ]
        },
        {
            "name":" UPLOAD_FILE",
            "data":[
                0,
                0,
                2,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            ]
        }
    ]
}