var responseTimeDistributions = 
{
    "categories":[
        "0ms",
        "10ms",
        "20ms",
        "30ms",
        "40ms",
        "50ms",
        "60ms",
        "70ms",
        "80ms"
    ],
    "distributions":[
        {
            "name":" GOTO_INDEX_PAGE",
            "data":[
                287,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            ]
        },
        {
            "name":" UPLOAD_FILE",
            "data":[
                0,
                57,
                129,
                10,
                35,
                22,
                2,
                11,
                13
            ]
        }
    ]
}